### ISSUE TITLE
Disk quota exceeded

### ISSUE THREAD

**Issue by YIN95** [Stanford-TML/EDGE#5]
![image](https://user-images.githubusercontent.com/35791079/229077058-a2fd054b-8dce-4e8b-ac5a-dd866550920d.png)

Hi! Thanks for sharing the impressive work. 
Could I ask how to solve this? I am processing the dataset by one A100, on a cluster. But it shows disk quota is exceeded, even if it is not true. 

Thank you in advance.

**Comment by minhnhatvt** [comment]
This is because the jukemirlib automatically downloads the jukebox model (which is about 10GB) into the '/usr/' directory or something like that (you can see this [line](https://github.com/rodrigo-castellon/jukemirlib/blob/98223a631f7327b4b45ed60f900e6a3a71130b25/jukemirlib/constants.py#L9)). I believe the disk quota of this directory is limited on your cluster, so I think you may want to change the cache_dir to the directory of your project for example.

**Comment by YIN95** [comment]
Actually, I could see the model can be downloaded successfully, but still has this problem (

**Comment by minhnhatvt** [comment]
That's weird, have you tried creating data by extracting only the baseline feature "--extract-baseline" but not "--extract-jukebox"?

**Comment by YIN95** [comment]
"--extract-baseline" works for me!
But "--extract-jukebox" encounters this issue.
