### ISSUE TITLE
About the geometric loss and data normalizer

### ISSUE THREAD

**Issue by minhnhatvt** [Stanford-TML/EDGE#8]
Hello authors, thank you for the very impressive work. 

I interestingly noticed that the code used a normalizer to preprocess the pose data vectors before training the model. Then in the FK forward pass to compute the Fk loss and the foot loss, I saw the lines to unnormalize the data ([L482-483](https://github.com/Stanford-TML/EDGE/blob/main/model/diffusion.py#L481)) was commented out. From my intuition, after normalizing, the rotations may not be valid rotations anymore.  So the FK forward may not work properly and I thought the pose should be unnormalized to fix this problem. I'm just not sure whether or not it is true for the case of 6D rotation, maybe I was wrong. Could you explain the reason for this? Thank you!

The reference code:

```
b, s, c = model_out.shape
# unnormalize
# model_out = self.normalizer.unnormalize(model_out)
# target = self.normalizer.unnormalize(target)
# X, Q
model_x = model_out[:, :, :3]
model_q = ax_from_6v(model_out[:, :, 3:].reshape(b, s, -1, 6))
target_x = target[:, :, :3]
target_q = ax_from_6v(target[:, :, 3:].reshape(b, s, -1, 6))
```

**Comment by jtseng20** [comment]
This is a good observation. This is sort of deep learning black magic, but I found that it didn't impact performance at all whether or not I unnormalized the data before applying the FK loss. True, the rotations will not be generally valid, but the FK computation will not crash since the matrix multiplication will still go through. So, I see it as the model learning to optimize this loss in a slightly transformed space that doesn't "make sense" if you consider it as joint angles, but still makes sense if you think of FK as an arbitrary function of matrices. I agree it would be cleaner for the reader if the unnormalize stayed in the code, but in the end it made no difference.
